# Generated by Django 5.1.5 on 2025-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='bank_slip',
            field=models.FileField(upload_to='bank_slips/'),
        ),
    ]
