# Generated by Django 5.1.5 on 2025-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0004_remove_userprofile_first_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='shares_count',
        ),
        migrations.AddField(
            model_name='deposit',
            name='remaining_shares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='shares_covered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='bank_slip',
            field=models.FileField(upload_to='deposits/'),
        ),
    ]
