# Generated by Django 5.1.5 on 2025-03-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0005_remove_deposit_shares_count_deposit_remaining_shares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='remaining_shares',
        ),
        migrations.AddField(
            model_name='deposit',
            name='committed_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='paid_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='remaining_share_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deposit',
            name='total_commitment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
