# Generated by Django 5.1.5 on 2025-03-20 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0007_monthlysharepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('deadline_day', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.RenameField(
            model_name='monthlysharepayment',
            old_name='payment_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='date_applied',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='committed_shares',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='paid_shares',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='remaining_share_balance',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='shares_covered',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='total_commitment',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='related_deposit',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='related_loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Loan duration in months'),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='bank_slip',
            field=models.FileField(upload_to='bank_slips/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='bank_slip',
            field=models.FileField(upload_to='payment_slips/'),
        ),
        migrations.AlterField(
            model_name='monthlysharepayment',
            name='payment_month',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='days_late',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='original_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_type',
            field=models.CharField(choices=[('LATE_DEPOSIT', 'Late Deposit'), ('MISSED_MEETING', 'Missed Meeting'), ('OTHER', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='source',
            field=models.CharField(choices=[('INTEREST', 'Loan Interest'), ('INVESTMENT', 'Investment Returns'), ('OTHER', 'Other Sources')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('LOAN_REQUEST', 'Loan Request'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_PAYMENT', 'Loan Payment'), ('PROFIT_DISTRIBUTION', 'Profit Distribution'), ('PENALTY', 'Penalty')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DistributionDetail',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
