# Generated by Django 5.1.5 on 2025-06-12 10:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0009_deposit_approval_date_deposit_rejected_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='remaining_balance_non_negative',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='total_interest',
            new_name='interest_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='confirmation_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='disbursement_slip',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration',
        ),
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 10, 18, 1, 556759, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('DISBURSED', 'Disbursed'), ('REPAID', 'Repaid'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20),
        ),
    ]
