# Generated by Django 5.1.5 on 2025-06-12 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0010_remove_loan_remaining_balance_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='monthlydeadline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlydeadline',
            name='deadline_day',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monthlydeadline',
            name='month',
            field=models.DateField(),
        ),
    ]
