# Generated by Django 5.1.5 on 2025-06-17 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0011_loan_duration_alter_monthlydeadline_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={'ordering': ['-distribution_date']},
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='description',
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='shares_distributed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='distribution_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='per_share_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
