# Generated by Django 5.1.5 on 2025-07-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0015_collectivefund_loan_disbursed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDistributionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(auto_now_add=True)),
                ('total_distributed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
