# Generated by Django 5.1.5 on 2025-07-09 14:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwizacash', '0016_profitdistributionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectivefund',
            name='available_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='collectivefund',
            name='total_profit_distributed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='collectivefund',
            name='total_profit_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
